config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  root 'home#index'
  resources :places do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :place
  validates :commentor, :body, presence:true
end

app/models/place.rb
class Place < ApplicationRecord
	validates :name, :latitude, :longtitude, presence:true
	has_many_attached :pictures
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    place = Place.find_by_id(params[:place_id])
    comment = place.comments.create(comment_params)
    redirect_to place
  end


  private

    def comment_params
      params.require(:comment).permit(:commentor, :body)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  include HomeHelper

  def index
    @places = Gmaps4rails.build_markers(Place.all) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longtitude
      marker.infowindow infowindow(place)
    end 
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    @places = Place.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to places_url, notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to places_url, notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longtitude, pictures:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper

def infowindow(place)
 "<img src='#{url_for(place.pictures.first)}'/> #{place.name}" 
end


end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/home/index.html.erb
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Come Across</h1>
        <p class="lead text-muted">A online web platform where you can add places of differnt categories like Landscape, People & Food visited by You. You can see all these places on Google Map.</p>
        <p>
          <a href="/places/new" class="btn btn-primary my-2">Add New Place</a>
          <a href="/places" class="btn btn-secondary">Places List</a>
        </p>
      </div>
    </div>
  </section>

  <section class="container">
    <div class="row py-lg-2">
      <div id="map" style='height: 900px;'></div>
    </div>
  </section>
</main>



<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function() {
    console.log(<%=raw @places.to_json %>)
    markers = handler.addMarkers(<%=raw @places.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComeAcross</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['google_api_key']}" %>
    <%= javascript_include_tag '//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js' %> 
    <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'%>
    <%= javascript_include_tag '//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>    
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: place) do |form| %>
  <% if place.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>
      <ul>
        <% place.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row mb-5">
    <%= form.label :name, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-6">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>


  <div class="form-group row mb-5">
    <%= form.label :latitude, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-6">
      <%= form.text_field :latitude, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row mb-5">
    <%= form.label :longtitude, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-6">
      <%= form.text_field :longtitude, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row mb-5">
    <%= form.label :pictures, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-6">
      <% 3.times do %>
        <%= form.file_field :pictures, multiple: true, class: 'form-control' %>
      <% end %>
    </div>
  </div>

  <div class="actions float-end">
    <%= form.submit :Save, class: 'btn btn-success' %>
    <a href="/" class="btn btn-secondary">Home</a>
  </div>


<% end %>

app/views/places/edit.html.erb
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-10 col-md-8 mx-auto">
        <h1 class="fw-light">Edit Place</h1>
        <div class="row py-lg-5 border">
          <%= render 'form', place: @place %>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/places/index.html.erb
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5 border">
      <div class="col-lg-12 col-md-8 mx-auto">
        <h1 class="fw-light">Visted Places</h1>
        <p id="notice"><%= notice %>
        <table class='table table-striped'>
          <thead class='thead-dark'>
            <tr>
              <th>Name</th>
              <th>Latitude</th>
              <th>Longtitude</th>
              <th>Photos</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @places.each do |place| %>
              <tr>
                <td><%= place.name %></td>
                <td><%= place.latitude %></td>
                <td><%= place.longtitude %></td>
                <td>
                  <% place.pictures.each do |pic| %>
                    <%= link_to image_tag(url_for(pic), width:"40", height:"40"),  url_for(pic), target:'_blank' %>
                  <% end %>
                <td><%= link_to 'Edit', edit_place_path(place),class: "btn btn-primary" %></td>
                <td><%= link_to 'Show', place_path(place),class: "btn btn-primary" %></td>
                <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>



        <p>
          <a href="/" class="btn btn-secondary">Home</a>
        </p>
      </div>
    </div>
  </section>
</main>

app/views/places/new.html.erb
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-10 col-md-8 mx-auto">
        <h1 class="fw-light">Add New Place</h1>
        <div class="row py-lg-5 border">
          <%= render 'form', place: @place %>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/places/show.html.erb
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light"><%= @place.name%>(<%= @place.latitude%>, <%= @place.longtitude%>)</h1>
        <p class="lead text-muted"></p>
        <p>
          <a href="/places/new" class="btn btn-primary my-2">Add New Place</a>
          <a href="/" class="btn btn-secondary">Home</a>
        </p>
      </div>
    </div>
  </section>

  <section class="container">
    <div class="row py-lg-2">
      <% @place.pictures.each do |pic| %>
        <div class="col-lg-4 col-md-8 mx-auto border">
          <%= image_tag(url_for(pic), height:"auto", width:"80%") %>
        </div>  
      <% end %>
    </div>
  </section>

  <section class="container py-5">
    <h4 class="fw-light">Add a Comment</h4>
    <div class="row py-lg-2 border">
      <div class="col-lg-6 col-md-8 mx-auto">        
        <%= form_with model: [@place, @place.comments.build] do |form|%>
          <div class="form-group row mb-5">
            <%= form.label :commentor, class: 'col-sm-2 col-form-label' %>
            <div class="col-sm-6">
              <%= form.text_field :commentor, class: 'form-control' %>
            </div>
          </div>        
        <div class="form-group row mb-5">
          <%= form.label :body, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-6">
            <%= form.text_field :body, class: 'form-control' %>
          </div>
        </div>
        <div class="actions float-end">
          <%= form.submit :Save, class: 'btn btn-success' %>
        </div>
        <%end%>
      </div>
    </div>
  </section>


  <section class="container">
    <h4 class="fw-light">Comments</h4>    
    <div class="row py-lg-2 border">
      <div class="col-lg-6 col-md-8">        
        <% @place.comments.order('id desc').each do |comment| %>
          <h6><%= comment.commentor %>:</h6>
          <p><%= comment.body %></p>
          <p class="text-muted"><%= time_ago_in_words(comment.created_at) %>ago</p>
        <%end%>
      </div>
    </div>
  </section>




</main>



<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function() {
    console.log(<%=raw @places.to_json %>)
    markers = handler.addMarkers(<%=raw @places.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/shared/_header.html.erb
<!-- inside app/views/welcome/index.html.erb -->  
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Collapsed content</h5>
    <span class="text-muted">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>